modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
modId = "pestilence"
version = "${file.jarVersion}"
logoFile = "pestilence.png"
authors = "TheValiantSquidward, DylanVHS, PlatypusHasNoHat, MrMouthington"
displayName = "Pestilence"
description = '''Adds rats. The rats are foul creatures of darkness. Have fun!'''

[[dependencies.pestilence]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pestilence]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "AFTER"
side = "BOTH"